"""Reusable, server-rendered editorial components; no browser framework required."""
import json
from html import escape as e
from pathlib import Path
from PIL import Image
ROOT = Path(__file__).resolve().parents[1]
P = json.loads((ROOT/'data/project.json').read_text(encoding='utf-8-sig'))
def image(name, alt, cls='', eager=False, sizes='100vw'):
    path = f'assets/img/{name}-1280.webp'
    w,h = Image.open(ROOT/path).size
    srcset = f'assets/img/{name}-640.webp 640w, {path} {w}w'
    if (ROOT/f'assets/img/{name}-1600.webp').exists(): srcset += f', assets/img/{name}-1600.webp 1600w'
    return f'<img class="{cls}" src="{path}" srcset="{srcset}" sizes="{sizes}" width="{w}" height="{h}" alt="{e(alt)}" loading="{"eager" if eager else "lazy"}" decoding="async" {"fetchpriority=high" if eager else ""}>'
MARK = (ROOT/'assets/img/logo-mark.svg').read_text(encoding='utf-8').replace('role="img" aria-label="Valencia Town"','aria-hidden="true" focusable="false"')
def todo(value, fallback='To be confirmed'):
    return f'<span class="tbc">{fallback}</span>' if str(value).startswith('TODO') else e(str(value))
def phone_href(): return 'tel:+' + ''.join(ch for ch in P['SALES_PHONE'] if ch.isdigit())
def mark(cls='brand-mark'): return f'<span class="{cls}">{MARK}</span>'
SITE_URL = P['siteUrl'].rstrip('/')  # single place to swap for the brand domain
def eyebrow(text): return f'<p class="eyebrow">{text}</p>'
def cta(label='Arrange a private visit', interest='Site Visit', cls='text-link'):
    return f'<button class="{cls}" data-enquiry="{interest}">{label}<span aria-hidden="true">↗</span></button>'
def header():
    return '''<a class="skip-link" href="#main">Skip to content</a><header class="header" id="header"><a class="wordmark" href="/" aria-label="Valencia Town home">'''+mark()+'''<span>VALENCIA<small>T O W N</small></span></a><nav class="desktop-nav" aria-label="Main navigation"><a href="#project">Project</a><a href="#masterplan">Masterplan</a><a href="#life">Life at Valencia</a><a href="#location">Location</a><a href="#faq">Questions</a></nav>'''+cta('Private visit',cls='nav-visit')+'''<button class="menu-toggle" aria-label="Open menu" aria-haspopup="dialog" aria-controls="mobile-menu"><span></span><span></span></button></header>
    <dialog id="mobile-menu" class="menu-dialog" aria-label="Navigation"><button class="close" data-close aria-label="Close menu">×</button><p class="eyebrow">VALENCIA TOWN</p><nav aria-label="Mobile navigation"><a href="#project"><small>01</small>The project</a><a href="#masterplan"><small>02</small>Masterplan</a><a href="#life"><small>03</small>Life at Valencia</a><a href="#location"><small>04</small>Location</a><a href="#faq"><small>05</small>Questions</a></nav>'''+cta()+'''<p class="menu-address">Shahna · Indore–Ujjain corridor<br>A place to put down roots.</p></dialog>'''
def hero():
    return f'''<section class="hero" aria-labelledby="hero-title"><div class="hero-media"><picture><source media="(max-width: 767px)" srcset="assets/img/grand-gate-portrait-480.webp 480w, assets/img/grand-gate-portrait-580.webp 580w" sizes="100vw">{image('grand-gate','Valencia Town entrance architecture at sunset — artist’s impression','hero-image',True)}</picture></div><div class="hero-shade"></div><div class="hero-content">{eyebrow('VALENCIA TOWN')}<h1 id="hero-title"><span>The address</span><span>of <em>tomorrow.</em></span></h1><div class="hero-bottom"><p>A place to put down roots,<br>between Indore and Ujjain.</p><div class="hero-actions">{cta(cls='button-light')}<a class="text-link" href="#project">Discover Valencia <span aria-hidden="true">↓</span></a></div></div></div><div class="hero-foot"><span>SHAHNA · INDORE–UJJAIN CORRIDOR</span><span>Artist’s impression</span></div></section>'''
def intro():
    return f'''<section class="idea section wrap" id="project"><div class="reveal">{eyebrow('THE IDEA')}<h2>Not just<br>a place to live.<br><em>A place to belong.</em></h2><p class="idea-copy">Envisioned around nature,<br>community and generations.</p></div><figure class="idea-image reveal">{image('arch-walkway','Sculptural walkway within Valencia Town’s landscaped gardens',sizes='(max-width: 767px) 65vw, 32vw')}</figure></section>'''
def scale():
    return f'''<section class="scale forest"><div class="wrap scale-inner">{eyebrow('SPACE FOR EVERYTHING STILL TO COME')}<div class="scale-composition"><div class="scale-number reveal">{P['acres']}<span>ACRES</span></div><div class="scale-copy reveal"><h2>One thoughtfully<br>planned <em>world.</em></h2></div></div><p class="scale-next reveal"><span>{P['plots']}</span> residential plots. One shared sense of belonging.</p></div></section>'''
def masterplan():
    return f'''<section class="section masterplan" id="masterplan"><div class="wrap"><div class="section-heading">{eyebrow('THE MASTERPLAN')}<h2>A neighbourhood,<br>considered <em>as one.</em></h2></div><div class="plan-image-wrap"><img src="assets/img/master-layout-832.webp" width="832" height="474" loading="lazy" alt="Valencia Town masterplan showing residential precincts and internal roads"><div id="plan-hotspots"></div></div><div class="plan-caption"><span>A CONNECTED COMMUNITY</span><button class="plan-expand" data-open-plan>Explore full plan <span aria-hidden="true">↗</span></button><span>Indicative layout · Artist’s impression</span></div><div class="plan-discovery"><figure class="plan-figure"><img id="plan-image" src="assets/img/{P['masterplan'][0]['image']}-640.webp" srcset="assets/img/{P['masterplan'][0]['image']}-640.webp 640w, assets/img/{P['masterplan'][0]['image']}-1280.webp 1280w" sizes="(max-width: 767px) 100vw, 42vw" width="640" height="360" alt="" loading="lazy" decoding="async"><figcaption>Artist’s impression</figcaption></figure><div class="plan-detail" id="plan-detail" aria-live="polite"><p class="eyebrow">01 / 08</p><h3>Grand entrance</h3><p>{P['masterplan'][0]['description']}</p></div><div class="discovery-controls"><button data-plan-prev aria-label="Explore previous place">←</button><button data-plan-next aria-label="Explore next place">→</button></div></div><div class="plan-links"><button class="text-link" data-open-plan>View full masterplan <span aria-hidden="true">↗</span></button>{cta('Request layout','Layout','button-dark')}</div></div></section>'''
def lifestyle():
    return f'''<section class="landscape" id="life">{image('garden-lawn','Open lawns and landscaped gardens at Valencia Town')}<div class="wrap landscape-copy reveal">{eyebrow('THE LANDSCAPE')}<h2>Room<br>to <em>breathe.</em></h2><p>Gardens, open spaces and quieter corners<br>woven into everyday life.</p></div></section><section class="community section wrap"><figure class="community-image reveal">{image('aerial-clubhouse','Valencia Town clubhouse and its landscaped approach',sizes='(max-width: 767px) 100vw, 60vw')}<figcaption>Artist’s impression</figcaption></figure><div class="community-copy reveal">{eyebrow('THE CLUB')}<h2>Designed for<br><em>coming together.</em></h2><p>For familiar faces, shared celebrations<br>and neighbours who become friends.</p></div></section>'''
def generations():
    return f'''<section class="generations forest"><div class="generation-image">{image('kids-play-area','Children’s play spaces and tree-lined paths at Valencia Town')}</div><div class="wrap generation-content reveal">{eyebrow('FOR EVERY GENERATION')}<h2>For today.<br>For everything<br><em>that comes next.</em></h2><p>Spaces for children to grow, families to connect<br>and generations to belong.</p></div></section>'''
def plots():
    return f'''<section class="plots section wrap" id="plots"><div class="reveal">{eyebrow('YOUR PLACE WITHIN VALENCIA')}<h2>Space to build<br><em>life your way.</em></h2></div><div class="plot-details reveal"><span class="plot-line-art" aria-hidden="true"><i></i><i></i><i></i></span><p class="eyebrow">RESIDENTIAL PLOTS</p><p class="plot-size">{P['plotSizes']}<small>square feet</small></p><p class="plot-price">Starting from ₹{todo(P['priceFrom'],'—')} lakh · {e(P['paymentPlan'])}</p><p class="fine">Approximate sizes. Availability changes.<br>Pricing on request.</p>{cta('Enquire about plots','Plot Availability','button-dark')}</div></section>'''
def location():
    return f'''<section class="location section" id="location"><div class="wrap location-grid"><div>{eyebrow('A PLACE IN BETWEEN')}<h2>Between<br>Indore <em>&amp; Ujjain.</em></h2><p class="editorial">Connected to the city.<br>Surrounded by space.</p><a class="text-link" href="https://www.google.com/maps/dir/?api=1&amp;destination={P['latitude']},{P['longitude']}" target="_blank" rel="noopener">Get directions <span aria-hidden="true">↗</span></a></div><div class="journey"><div class="map-embed" id="map-embed"><button class="map-load" data-load-map aria-label="Load the interactive map">{mark('map-mark')}<span>Load the map</span><small>Indore–Ujjain Road · SAIMS · Vijay Nagar · Airport · Ujjain</small></button></div><div class="route-axis" aria-label="Valencia Town at Shahna, between Indore and Ujjain"><span class="route-city">INDORE</span><div class="route-valencia"><strong>VALENCIA TOWN</strong><small>SHAHNA · YOUR PLACE IN BETWEEN</small></div><span class="route-city">UJJAIN</span></div><ul class="route-list">{''.join(f'<li><span>{"Sri Aurobindo Hospital (SAIMS)" if k=="SAIMS" else k}</span><span>{v} min</span></li>' for k,v in P['distances'].items())}</ul><p class="fine">Schematic route, not to scale. Drive times are approximate and may vary according to traffic and route.</p></div></div></section>'''
def film():
    return f'''<section class="film forest section" id="film"><div class="wrap"><div class="film-heading">{eyebrow('THE FILM')}<h2>Experience<br><em>Valencia.</em></h2></div><button class="film-poster" data-open-film aria-label="Play the Valencia Town 3D walkthrough">{image('gate-sunset','Sunset at Valencia Town’s entrance — play the 3D walkthrough')}<span class="play-icon" aria-hidden="true">▷</span><span class="film-caption">WATCH THE WALKTHROUGH <span>3D FILM</span></span></button></div></section>'''
def gallery():
    assets=[('flower-garden','Gardens in bloom'),('arch-walkway','A walk through the gardens'),('sports-court','Room to play'),('signage-wall','A sense of arrival')]
    return f'''<section class="gallery section wrap" id="gallery"><div class="section-heading">{eyebrow('A CLOSER LOOK')}<h2>A sense <em>of place.</em></h2></div><div class="gallery-grid">{''.join(f'<figure class="gallery-item gallery-item-{i+1}"><button data-gallery="{i}" aria-label="Enlarge {alt.lower()}">{image(img,alt,sizes="(max-width: 767px) 85vw, (max-width: 1440px) 860px, 65vw")}<span class="gallery-plus" aria-hidden="true">↗</span></button><figcaption><span>{i+1:02} / {alt}</span><span>Artist’s impression</span></figcaption></figure>' for i,(img,alt) in enumerate(assets))}</div><p class="mobile-gallery-hint">SWIPE TO EXPLORE <span aria-hidden="true">→</span></p></section>'''
def visit():
    return f'''<section class="visit forest" id="visit">{image('entrance-road','Tree-lined entrance road into Valencia Town at dusk','visit-image')}<div class="visit-shade"></div><div class="wrap visit-content">{eyebrow('YOUR NEXT CHAPTER')}<h2>Come see<br><em>Valencia.</em></h2><p>Some places are better experienced<br>than explained.</p><div class="visit-actions">{cta(cls='button-light')}{cta('Request brochure','Brochure')}</div>{mark('visit-mark')}</div></section>'''
def faqs():
    d=P['distances']
    return [('Where is Valencia Town located?','Valencia Town is at Shahna on the Indore–Ujjain Road in Madhya Pradesh, between Indore and Ujjain.'),('What plot sizes are offered?',f'Residential plots are approximately {P["plotSizes"]} sq ft. Current sizes and availability can be confirmed with the sales team.'),('What is planned within the community?','The planned amenities include a clubhouse, temple, children’s playground, forest-style gardens, sports courts, landscaped lawns, senior citizens’ library, meeting zone, women’s activity zone, wide internal roads and gated security. Specifications and layouts are indicative and subject to change.'),('How well connected is the location?',f'Sri Aurobindo Hospital (SAIMS) is approximately {d["SAIMS"]} minutes away, Vijay Nagar and Indore Airport approximately {d["Vijay Nagar"]} minutes, and Ujjain approximately {d["Ujjain"]} minutes. Times vary with traffic and route.'),('How can I arrange a private visit?','Use Arrange a Private Visit and leave your name and mobile number. The team can help with a visit, current plot availability or a brochure.'),('Where can I check approvals and project details?','Request the current project documentation and applicable approvals from the sales team before making a decision. The communicated project scale is '+P['investment'].lower()+'.')]
def faq():
    return f'''<section class="faq section wrap" id="faq"><div class="faq-intro">{eyebrow('A FEW THINGS TO KNOW')}<h2>Questions,<br><em>answered.</em></h2><p>The essentials, in brief. For anything else, the Valencia team is a conversation away.</p><button class="button-dark" data-enquiry="Site Visit" data-call>Speak to the team<span aria-hidden="true">↗</span></button></div><div class="faq-list">{''.join(f'<details><summary>{e(q)}<span aria-hidden="true">+</span></summary><div class="faq-answer"><p>{e(a)}</p></div></details>' for q,a in faqs())}</div></section><section class="seo wrap"><details><summary>Read more about the location <span aria-hidden="true">+</span></summary><div><h3>Residential plots on the Indore–Ujjain Road</h3><p>For families exploring residential plots near Indore or Ujjain, Valencia Town brings together planned community spaces and room to build a personal home. Its Shahna address on the Indore–Ujjain corridor connects the township with Sri Aurobindo Hospital (SAIMS), Vijay Nagar and the wider region.</p><p>When considering plots on Indore–Ujjain Road, explore the location in person, review current layout documentation and confirm available plot sizes. Our team can help you understand the planned amenities and arrange a private visit.</p></div></details></section>'''
def developer():
    D=P['developer']
    tes=[t for t in P['testimonials'] if not str(t['quote']).startswith('TODO')]
    tes_html=''
    if tes:
        items=[]
        for t in tes:
            items.append('<blockquote><p>“'+e(t['quote'])+'”</p><footer>'+e(t['name'])+'<span>'+e(t['detail'])+'</span></footer></blockquote>')
        tes_html='<div class="testimonials">'+''.join(items)+'</div>'
    prog=[x for x in P['progressPhotos'] if (ROOT/('assets/img/'+x.get('image','')+'-1280.webp')).exists()]
    prog_html=''
    if prog:
        items=[]
        for x in prog:
            items.append('<figure>'+image(x['image'],x['caption'],sizes='(max-width: 767px) 85vw, 32vw')+'<figcaption>'+e(x['caption'])+' · '+e(x['date'])+'</figcaption></figure>')
        prog_html='<div class="progress-grid">'+''.join(items)+'</div>'
    past=', '.join(todo(x) for x in D['pastProjects']); banks=', '.join(todo(x) for x in D['bankTieUps'])
    return f'''<section class="developer section wrap" id="developer"><div class="developer-intro">{eyebrow('THE DEVELOPER')}<h2>Built by people<br>who <em>stay.</em></h2><p>{todo(D['name'])}, part of {todo(D['group'])}. Developing in the region since {todo(D['since'])}.</p></div><dl class="facts"><div><dt>Past projects</dt><dd>{past}</dd></div><div><dt>Construction status</dt><dd>{todo(D['constructionStatus'])}</dd></div><div><dt>Possession</dt><dd>{todo(D['possession'])}</dd></div><div><dt>Bank tie-ups</dt><dd>{banks}</dd></div><div><dt>Sales gallery</dt><dd>{todo(D['salesGallery'])}<br>{e(D['hours'])}</dd></div><div><dt>Speak to us</dt><dd><a href="{phone_href()}">{e(P['SALES_PHONE'])}</a><br><a href="mailto:{e(P['SALES_EMAIL'])}">{e(P['SALES_EMAIL'])}</a></dd></div></dl>{tes_html}{prog_html}</section>'''
def footer():
    return f'''<footer class="footer forest"><div class="wrap"><div class="footer-grid"><div class="footer-brand">{mark('footer-mark')}<a href="#" class="footer-wordmark" aria-label="Valencia Town home">VALENCIA<span>T O W N</span></a><p class="footer-tagline">{P['tagline']}</p></div><div class="footer-col"><p class="eyebrow">EXPLORE</p><nav aria-label="Footer"><a href="#project">The project</a><a href="#masterplan">Masterplan</a><a href="#life">Life at Valencia</a><a href="#location">Location</a><a href="#faq">Questions</a></nav></div><div class="footer-col"><p class="eyebrow">VISIT</p><address>Valencia Town<br>Shahna, Indore–Ujjain Road<br>Madhya Pradesh</address><a class="text-link" href="https://www.google.com/maps/dir/?api=1&amp;destination={P['latitude']},{P['longitude']}" target="_blank" rel="noopener">Get directions <span aria-hidden="true">↗</span></a></div><div class="footer-col footer-connect"><p class="eyebrow">CONNECT</p><p>Private visits by appointment.<br>Brochure and layout on request.</p><div id="contact-details"></div><a class="whatsapp footer-whatsapp" hidden target="_blank" rel="noopener">WhatsApp us <span aria-hidden="true">↗</span></a>{cta(cls='button-light')}<p id="rera-line" hidden></p></div></div><div class="footer-legal"><p>Images are artist’s impressions for representation purposes. Specifications, amenities and layouts are indicative and subject to change.</p><span>© <span id="year">2026</span> Valencia Town · {todo(P['legalEntity'],'Legal entity to be confirmed')}</span><button class="privacy-link" data-privacy>Privacy</button><button class="privacy-link" data-terms>Terms</button></div></div><p class="footer-giant" aria-hidden="true">VALENCIA</p></footer><div class="mobile-visit"><a class="call-link" href="{phone_href()}"><span aria-hidden="true">☏</span>Call</a><a class="whatsapp" hidden aria-label="Contact Valencia Town on WhatsApp" target="_blank" rel="noopener">WhatsApp</a>{cta('Private visit',cls='bar-visit')}</div><a class="desktop-whatsapp whatsapp" hidden aria-label="Contact Valencia Town on WhatsApp" target="_blank" rel="noopener">WhatsApp ↗</a>'''
def modals():
    return '''<dialog id="enquiry-modal" class="enquiry-dialog" aria-labelledby="enquiry-title"><button class="close" data-close aria-label="Close enquiry">×</button><div class="enquiry-intro"><p class="eyebrow">YOUR NEXT CHAPTER</p><h2 id="enquiry-title">Let’s put down<br><em>roots.</em></h2><p>A little about you. The beginning of a conversation.</p></div><form id="enquiry-form" method="post" action="#" novalidate><label for="full-name">Full name</label><input id="full-name" name="name" autocomplete="name" minlength="2" maxlength="80" required placeholder="Your full name"><label for="mobile-number">Mobile number</label><div class="phone-field"><span>+91</span><input id="mobile-number" name="phone" type="tel" autocomplete="tel-national" inputmode="tel" maxlength="16" required pattern="(?:\\+91[ -]?)?[6-9][0-9 -]{9,13}" placeholder="10-digit mobile number" aria-describedby="phone-help"></div><small id="phone-help">Indian mobile number, with or without +91.</small><label for="email">Email <span class="optional">optional</span></label><input id="email" name="email" type="email" autocomplete="email" maxlength="120" placeholder="you@example.com"><label for="preferred-time">Preferred time to call <span class="optional">optional</span></label><select id="preferred-time" name="preferredTime"><option value="">Any time</option><option>Morning (10 am – 1 pm)</option><option>Afternoon (1 pm – 4 pm)</option><option>Evening (4 pm – 7 pm)</option></select><label for="interest">I’m interested in</label><select id="interest" name="interest"><option>Site Visit</option><option>Price List</option><option>Brochure</option><option>Plot Availability</option><option>Layout</option></select><div class="honeypot" aria-hidden="true"><label>Leave empty<input name="website" tabindex="-1" autocomplete="off"></label></div><p class="form-consent">By sending this request, you agree to be contacted about Valencia Town. <button type="button" data-privacy>Privacy details</button></p><button class="button-dark" type="submit">Send request <span aria-hidden="true">↗</span></button><p id="form-status" role="status" aria-live="polite"></p></form><div id="enquiry-success" hidden><span class="success-mark" aria-hidden="true">✓</span><h3>A new beginning.</h3><p>Your request has been received. The Valencia team will be in touch to help with your next step.</p><div class="next-steps"><a id="success-download" class="button-dark" hidden download>Download now <span aria-hidden="true">↓</span></a><a id="success-whatsapp" class="text-link whatsapp" hidden target="_blank" rel="noopener">Continue on WhatsApp <span aria-hidden="true">↗</span></a></div><button class="text-link" data-close>Back to Valencia <span aria-hidden="true">↗</span></button></div></dialog>
    <dialog id="plan-modal" class="viewer-dialog" aria-labelledby="plan-title"><div class="viewer-bar"><h2 id="plan-title">The masterplan</h2><button class="close" data-close aria-label="Close masterplan">×</button></div><div class="zoom-controls"><button data-zoom="out" aria-label="Zoom out">−</button><output id="zoom-level">100%</output><button data-zoom="in" aria-label="Zoom in">+</button><button data-zoom="reset">Reset</button></div><div class="plan-pan" tabindex="0" aria-label="Zoomable masterplan. Use plus and minus to zoom, scroll or drag to pan."><img id="zoom-image" src="assets/img/master-layout-832.webp" alt="Full Valencia Town masterplan" width="832" height="474"></div><p class="viewer-note">Use + to zoom. Drag or scroll to explore. Pinch to zoom on touch screens.<br>Indicative layout · Request the current layout for plot-level details.</p></dialog>
    
    <dialog id="gallery-modal" class="viewer-dialog gallery-dialog" aria-labelledby="gallery-caption"><button class="close" data-close aria-label="Close gallery">×</button><div class="gallery-viewer"><button data-gallery-prev aria-label="Previous image">←</button><img id="gallery-image" alt=""><button data-gallery-next aria-label="Next image">→</button></div><div class="gallery-viewer-caption"><p id="gallery-caption" aria-live="polite"></p><span>Artist’s impression</span><span id="gallery-count"></span></div></dialog>
    <dialog id="privacy-modal" class="privacy-dialog" aria-labelledby="privacy-title"><button class="close" data-close aria-label="Close privacy details">×</button><p class="eyebrow">YOUR INFORMATION</p><h2 id="privacy-title">A private conversation.</h2><p><strong>Purpose.</strong> When you send a request, your name, mobile number, optional email, preferred time and selected interest are used by the Valencia Town sales team only to respond to that request. The page you were on and campaign referral details may be recorded with it.</p><p><strong>Retention.</strong> Enquiry details are kept for up to 24 months, or until you ask us to remove them, whichever is sooner. They are not sold or shared with third parties for their own marketing.</p><p><strong>Your choices.</strong> To correct or delete your details, write to <a href="mailto:'''+e(P['SALES_EMAIL'])+'''">'''+e(P['SALES_EMAIL'])+'''</a> or tell the team member who contacts you. Please do not include sensitive personal information in your request.</p><p class="fine">Images are artist’s impressions for representation purposes. Specifications, amenities and layouts are indicative and subject to change. <button type="button" class="inline-link" data-terms>Terms of use</button></p></dialog>
    <dialog id="terms-modal" class="privacy-dialog" aria-labelledby="terms-title"><button class="close" data-close aria-label="Close terms">×</button><p class="eyebrow">TERMS OF USE</p><h2 id="terms-title">The small print.</h2><p>This website is for information only and does not constitute an offer, invitation or legal commitment. All images are artist’s impressions. Dimensions, areas, amenities, specifications, layouts and drive times are indicative and subject to change without notice.</p><p>Prices, availability and payment plans are confirmed only in writing by '''+todo(P['legalEntity'],'the developer')+'''. Please verify the current project documentation and applicable approvals before making any decision.</p><p class="fine tbc">TODO: legal team to review and complete these terms before launch.</p></dialog>'''
def document():
    url=SITE_URL; description=f'VALENCIA — The Address of Tomorrow. Explore Valencia Town, a {P["acres"]}-acre planned community with residential plots at Shahna on the Indore–Ujjain Road.'
    schema={'@context':'https://schema.org','@graph':[{'@type':'Place','name':P['name'],'url':url+'/', 'description':description,'address':{'@type':'PostalAddress','streetAddress':'Indore–Ujjain Road','addressLocality':'Shahna','addressRegion':'Madhya Pradesh','addressCountry':'IN'},'geo':{'@type':'GeoCoordinates','latitude':P['latitude'],'longitude':P['longitude']}},{'@type':'FAQPage','mainEntity':[{'@type':'Question','name':q,'acceptedAnswer':{'@type':'Answer','text':a}} for q,a in faqs()]}]}
    head=f'''<!doctype html><html lang="en-IN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"><title>Valencia Town | The Address of Tomorrow · Shahna</title><meta name="description" content="{description}"><meta name="theme-color" content="#17231D"><meta name="robots" content="index, follow, max-image-preview:large"><link rel="canonical" href="{url}/"><meta property="og:type" content="website"><meta property="og:locale" content="en_IN"><meta property="og:site_name" content="Valencia Town"><meta property="og:title" content="VALENCIA — The Address of Tomorrow"><meta property="og:description" content="{description}"><meta property="og:url" content="{url}/"><meta property="og:image" content="{url}/assets/img/og-image.jpg"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="VALENCIA — The Address of Tomorrow"><meta name="twitter:description" content="{description}"><meta name="twitter:image" content="{url}/assets/img/og-image.jpg"><link rel="icon" href="assets/img/favicon.svg" type="image/svg+xml"><link rel="icon" href="assets/img/favicon.ico" sizes="32x32"><link rel="apple-touch-icon" href="assets/img/apple-touch-icon.png"><link rel="preload" href="assets/fonts/cormorant.woff2" as="font" type="font/woff2" crossorigin><link rel="preload" href="assets/fonts/cormorant-italic.woff2" as="font" type="font/woff2" crossorigin><link rel="preload" href="assets/fonts/dmsans.woff2" as="font" type="font/woff2" crossorigin><link rel="preload" as="image" href="assets/img/grand-gate-1280.webp" imagesrcset="assets/img/grand-gate-640.webp 640w, assets/img/grand-gate-1280.webp 1280w" imagesizes="100vw" fetchpriority="high"><link rel="stylesheet" href="css/style.css?v=20261007f"><script type="application/ld+json">{json.dumps(schema,ensure_ascii=False)}</script></head>'''
    return head+'<body>'+header()+'<main id="main">'+''.join(f() for f in [hero,intro,scale,masterplan,lifestyle,generations,plots,location,gallery,visit,faq,developer])+'</main>'+footer()+modals()+f'<script id="project-data" type="application/json">{json.dumps(P,ensure_ascii=False).replace("<","&lt;")}</script><script src="js/main.js?v=20261007f" defer></script></body></html>'
