"""Reusable, server-rendered editorial components; no browser framework required."""
import json
from html import escape as e
from pathlib import Path
from PIL import Image
ROOT = Path(__file__).resolve().parents[1]
P = json.loads((ROOT/'data/project.json').read_text(encoding='utf-8-sig'))
def image(name, alt, cls='', eager=False, sizes='100vw'):
    path = f'assets/img/{name}-1280.webp'
    w,h = Image.open(ROOT/path).size
    srcset = f'assets/img/{name}-640.webp 640w, {path} {w}w'
    if (ROOT/f'assets/img/{name}-1600.webp').exists(): srcset += f', assets/img/{name}-1600.webp 1600w'
    return f'<img class="{cls}" src="{path}" srcset="{srcset}" sizes="{sizes}" width="{w}" height="{h}" alt="{e(alt)}" loading="{"eager" if eager else "lazy"}" decoding="async" {"fetchpriority=high" if eager else ""}>'
MARK = (ROOT/'assets/img/logo-mark.svg').read_text(encoding='utf-8').replace('role="img" aria-label="Valencia Town"','aria-hidden="true" focusable="false"')
def todo(value, fallback='To be confirmed'):
    return f'<span class="tbc">{fallback}</span>' if str(value).startswith('TODO') else e(str(value))
MAHAKAL_ART = (ROOT/'assets/img/mahakal-line.svg').read_text(encoding='utf-8').replace('<svg ','<svg class="mahakal-svg" ',1)
def phone_href(): return 'tel:+' + ''.join(ch for ch in P['SALES_PHONE'] if ch.isdigit())
WA_ICON = '<svg class="wa-icon" viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path fill="currentColor" d="M17.47 14.38c-.3-.15-1.76-.87-2.03-.97-.27-.1-.47-.15-.67.15-.2.3-.77.97-.94 1.17-.17.2-.35.22-.64.07-.3-.15-1.26-.46-2.4-1.48-.88-.79-1.48-1.76-1.65-2.06-.17-.3-.02-.46.13-.6.13-.14.3-.35.45-.52.15-.17.2-.3.3-.5.1-.2.05-.37-.03-.52-.07-.15-.67-1.6-.91-2.2-.24-.58-.49-.5-.67-.5h-.57c-.2 0-.52.07-.8.37-.27.3-1.04 1.02-1.04 2.48s1.07 2.88 1.22 3.08c.15.2 2.1 3.2 5.08 4.49.71.3 1.26.49 1.7.63.71.22 1.36.19 1.87.12.57-.09 1.76-.72 2.01-1.42.25-.7.25-1.29.17-1.42-.07-.12-.27-.2-.57-.35M12.05 21.78h-.01a9.87 9.87 0 0 1-5.03-1.38l-.36-.21-3.74.98 1-3.65-.24-.37a9.86 9.86 0 0 1-1.51-5.26c0-5.45 4.44-9.88 9.9-9.88 2.64 0 5.12 1.03 6.99 2.9a9.82 9.82 0 0 1 2.89 6.99c0 5.45-4.44 9.88-9.89 9.88m8.41-18.3A11.82 11.82 0 0 0 12.05 0C5.5 0 .16 5.33.16 11.89c0 2.1.55 4.14 1.59 5.94L0 24l6.3-1.65a11.9 11.9 0 0 0 5.74 1.46h.01c6.55 0 11.89-5.33 11.89-11.89 0-3.18-1.24-6.16-3.48-8.41"/></svg>'
def mark(cls='brand-mark'): return f'<span class="{cls}">{MARK}</span>'
SITE_URL = P['siteUrl'].rstrip('/')  # single place to swap for the brand domain
def eyebrow(text): return f'<p class="eyebrow">{text}</p>'
def cta(label='Arrange a private visit', interest='Site Visit', cls='link'):
    return f'<button class="{cls}" data-enquiry="{interest}">{label}</button>'
def frame_image(name, alt, eager=False, portrait=None):
    """Full-bleed render behind a chapter. A portrait crop is served on phones when one exists."""
    img = image(name, alt, 'frame-media', eager)
    if portrait:
        return f'<picture class="frame-pic"><source media="(max-width: 767px)" srcset="assets/img/{portrait}-480.webp 480w, assets/img/{portrait}-580.webp 580w" sizes="100vw">{img}</picture>'
    return img
def header():
    return '''<a class="skip-link" href="#main">Skip to content</a><header class="header" id="header"><a class="wordmark" href="/">'''+mark()+'''<span>Valencia Town</span></a><nav class="desktop-nav" aria-label="Main navigation"><a href="#mahakal">Mahakal</a><a href="#location">The road</a><a href="#plan">The plan</a><a href="#life">Life here</a><a href="#plots">Plots</a><a href="#faq">Questions</a></nav>'''+cta('Private visit',cls='nav-visit')+'''<button class="menu-toggle" aria-label="Open menu" aria-haspopup="dialog" aria-controls="mobile-menu"><span></span><span></span></button></header>
    <dialog id="mobile-menu" class="menu-dialog" aria-label="Navigation"><button class="close" data-close aria-label="Close menu">×</button>'''+mark('menu-mark')+'''<nav aria-label="Mobile navigation"><a href="#mahakal">Mahakal is calling</a><a href="#location">The road</a><a href="#plan">The plan</a><a href="#life">Life here</a><a href="#plots">Your plot</a><a href="#faq">Questions</a></nav>'''+cta(cls='btn')+'''<p class="menu-address">Shahna, Indore–Ujjain Road<br>Forty minutes from Shri Mahakaleshwar</p></dialog>'''
def hero():
    return f'''<section class="frame hero" id="top" aria-labelledby="hero-title">{frame_image('hero-signage','Valencia Town sales gallery at dusk with the illuminated Valencia Town sign, an artist’s impression',True,'hero-signage-portrait')}<div class="frame-copy"><h1 id="hero-title" class="display"><span>Valencia.</span><em>The Address of Tomorrow.</em></h1><p class="lede">Forty-eight acres of residential plots at Shahna on the Indore–Ujjain Road, forty minutes from Shri Mahakaleshwar. Mahakal is calling you home.</p><div class="actions">{cta('Plan your darshan and site visit',cls='btn')}<a class="link" href="#mahakal">Begin the story</a></div><dl class="facts"><div><dt>Acres</dt><dd>{P['acres']}</dd></div><div><dt>Residential plots</dt><dd>{P['plots']}</dd></div><div><dt>Minutes to Ujjain</dt><dd>{P['distances']['Ujjain']}</dd></div></dl></div><p class="frame-note">Artist’s impression</p></section>'''
def mahakal():
    return f'''<section class="calling" id="mahakal" aria-labelledby="calling-title"><div class="wrap calling-grid"><figure class="mahakal-art reveal">{MAHAKAL_ART}</figure><div class="calling-copy"><p class="hero-sign" lang="hi">जय श्री महाकाल</p><h2 id="calling-title" class="display"><span>Mahakal is calling</span><em>you home.</em></h2><p class="lede">Some come for a darshan. Some stay for a lifetime. Every year, crores of devotees travel to Ujjain; at Valencia Town the dawn Bhasma Aarti is a morning drive. For families anywhere in India, a rare chance to own a home where faith lives next door.</p><p class="day-title">A day, forty minutes from darshan.</p><ol class="day"><li><span class="day-when">4 am</span><span class="day-what">Bhasma Aarti at Shri Mahakaleshwar, the only one of its kind among the twelve Jyotirlingas.</span></li><li><span class="day-when">Sunrise</span><span class="day-what">The drive home along the Indore–Ujjain Road, about forty minutes.</span></li><li><span class="day-when">All year</span><span class="day-what">Shravan Mondays, Mahashivratri, Nag Panchami: every festival within reach, not a journey away.</span></li><li><span class="day-when">2028</span><span class="day-what">Simhastha, the Kumbh of Ujjain, at your doorstep.</span></li></ol><div class="actions">{cta('Plan your darshan and site visit',cls='btn')}</div><p class="fine">Drive time is approximate and varies with traffic and festival crowds. Not an assurance of future value.</p></div></div></section>'''
def location():
    d=P['distances']
    stops=[('Sri Aurobindo Hospital',d['SAIMS']),('Vijay Nagar, Indore',d['Vijay Nagar']),('Indore Airport',d['Indore Airport']),('Mahakaleshwar, Ujjain',d['Ujjain'])]
    return f'''<section class="frame road" id="location" aria-labelledby="road-title">{frame_image('entrance-road','Tree-lined entrance road into Valencia Town at dusk')}<div class="frame-copy"><h2 id="road-title" class="display"><span>Between Indore</span><em>and Ujjain.</em></h2><p class="lede">Shahna sits on the Indore–Ujjain Road. Indore’s hospitals, schools and airport on one side. Mahakal’s Ujjain on the other.</p><ul class="drive">{''.join(f'<li><strong>{m}<small>min</small></strong><span>{e(n)}</span></li>' for n,m in stops)}</ul><div class="actions"><a class="btn btn-ghost" href="https://www.google.com/maps/dir/?api=1&amp;destination={P['latitude']},{P['longitude']}" target="_blank" rel="noopener">Get directions</a></div><div class="map-embed" id="map-embed"><button class="link" data-load-map>Show the map here</button></div><p class="fine">Drive times are approximate and vary with traffic and route.</p></div><p class="frame-note">Artist’s impression</p></section>'''
def plan():
    return f'''<section class="frame plan" id="plan" aria-labelledby="plan-title"><video class="plan-video frame-media" muted loop playsinline preload="none" poster="assets/img/master-layout-832.webp" width="832" height="464" aria-label="Aerial walkthrough of the Valencia Town masterplan"><source data-src="assets/video/walkthrough.mp4" type="video/mp4"></video><div class="frame-copy"><h2 id="plan-title" class="display"><span>Forty-eight acres,</span><em>planned as one.</em></h2><p class="lede">About a thousand residential plots from {P['plotSizes']} square feet, with a clubhouse, a temple, forest gardens, sports courts, children’s play areas and wide internal roads.</p><div class="actions"><button class="btn" data-open-plan>Explore the full plan</button>{cta('Request the layout','Layout')}</div></div><p class="frame-note">Indicative layout, artist’s impression</p></section>
<section class="frame walk" id="walk" aria-labelledby="walk-title"><img id="plan-image" class="frame-media" src="assets/img/{P['masterplan'][0]['image']}-1280.webp" srcset="assets/img/{P['masterplan'][0]['image']}-640.webp 640w, assets/img/{P['masterplan'][0]['image']}-1280.webp 1280w" sizes="100vw" width="1280" height="622" alt="" loading="lazy" decoding="async"><div class="frame-copy"><p class="walk-label">Walk the plan</p><div class="plan-detail" id="plan-detail" aria-live="polite"><p class="eyebrow">01 / 08</p><h3 id="walk-title">Grand entrance</h3><p>{P['masterplan'][0]['description']}</p></div><div class="walk-controls"><button data-plan-prev aria-label="Previous place">←</button><button data-plan-next aria-label="Next place">→</button></div></div><p class="frame-note">Artist’s impression</p></section>'''
def life():
    frames=[('garden-lawn','Open lawns and landscaped gardens at Valencia Town','Room<br>to breathe.','Gardens, open lawns and quieter corners woven into everyday life.','life'),('aerial-clubhouse','Valencia Town clubhouse and its landscaped approach','A club for<br>coming together.','Familiar faces, shared celebrations and neighbours who become friends.',''),('kids-play-area','Children’s play spaces and tree-lined paths at Valencia Town','For today, and<br>everything after.','Space for children to grow, families to connect and generations to belong.','')]
    out=''
    for img,alt,h,p,i in frames:
        out+=f'''<section class="frame life"{' id="life"' if i else ''}>{frame_image(img,alt)}<div class="frame-copy"><h2 class="display display-s">{h}</h2><p class="lede">{p}</p></div><p class="frame-note">Artist’s impression</p></section>'''
    return out
def gallery():
    assets=[('flower-garden','Gardens in bloom'),('arch-walkway','A walk through the gardens'),('sports-court','Room to play'),('grand-gate','The grand entrance')]
    return f'''<section class="gallery" id="gallery" aria-labelledby="gallery-title"><div class="wrap gallery-head"><h2 id="gallery-title" class="display display-s">A closer look.</h2><p class="lede">Four views of the township as it is planned. Tap any image to see it in full.</p></div><div class="gallery-strip">{''.join(f'<figure class="gallery-item"><button data-gallery="{i}" aria-label="Enlarge {alt.lower()}">{image(img,alt,sizes="(max-width: 767px) 86vw, 62vw")}</button><figcaption>{alt}</figcaption></figure>' for i,(img,alt) in enumerate(assets))}</div></section>'''
def plots():
    price='' if str(P['priceFrom']).startswith('TODO') else f'<p class="plot-price">Starting from ₹{e(str(P["priceFrom"]))} lakh. {e(P["paymentPlan"])}.</p>'
    return f'''<section class="frame plots" id="plots" aria-labelledby="plots-title">{frame_image('internal-road','Wide internal road within Valencia Town')}<div class="frame-copy"><h2 id="plots-title" class="display"><span>Space to build</span><em>life your way.</em></h2><p class="plot-size">{P['plotSizes']}<small>square feet</small></p>{price}<p class="lede">Residential plots in a gated township, with a flexible payment plan. Sizes are approximate and availability changes, so ask the team for what is open today.</p><div class="actions">{cta('Ask about available plots','Plot Availability','btn')}{cta('Request the price list','Price List')}</div></div><p class="frame-note">Artist’s impression</p></section>'''
def visit():
    return f'''<section class="frame visit" id="visit" aria-labelledby="visit-title">{frame_image('gate-sunset','Sunset at Valencia Town’s entrance gate')}<div class="frame-copy"><h2 id="visit-title" class="display"><span>Come and see</span><em>Valencia.</em></h2><p class="lede">Walk the avenues. Stand on your plot. Then drive on to Ujjain for darshan. Private visits are by appointment, any day between 10 am and 7 pm.</p><div class="actions">{cta(cls='btn')}{cta('Request the brochure','Brochure')}</div></div><p class="frame-note">Artist’s impression</p></section>'''
def faqs():
    d=P['distances']
    return [('Where is Valencia Town?','Valencia Town is at Shahna on the Indore–Ujjain Road in Madhya Pradesh, between Indore and Ujjain.'),('How far is it from Mahakaleshwar Temple?',f'About {d["Ujjain"]} minutes by road to Ujjain, home of the Mahakaleshwar Jyotirlinga. Families visiting from anywhere in India can combine a darshan with a site visit. Drive times vary with traffic, route and festival crowds.'),('What plot sizes are offered?',f'Residential plots of approximately {P["plotSizes"]} square feet. The sales team can confirm current sizes and availability.'),('What is planned within the township?','A clubhouse, temple, children’s play areas, forest-style gardens, sports courts, landscaped lawns, a senior citizens’ library, meeting and women’s activity zones, wide internal roads and gated security. Specifications and layouts are indicative and subject to change.'),('How well connected is it to Indore?',f'Sri Aurobindo Hospital is about {d["SAIMS"]} minutes away, and Vijay Nagar and Indore Airport about {d["Vijay Nagar"]} minutes. Times vary with traffic and route.'),('How do I arrange a visit?','Use any “Arrange a private visit” button and leave your name and mobile number. The team will call to fix a time, and can also send the brochure, layout or price list.'),('Where can I check approvals and project details?','Ask the sales team for the current project documentation and applicable approvals before making a decision. The communicated project scale is '+P['investment'].lower()+'.')]
def faq():
    return f'''<section class="faq" id="faq" aria-labelledby="faq-title"><div class="wrap faq-grid"><div class="faq-intro"><h2 id="faq-title" class="display display-s">Questions,<br>answered.</h2><p class="lede">The essentials in brief. For anything else, the Valencia team is a phone call away.</p><button class="btn btn-ghost" data-enquiry="Site Visit" data-call>Speak to the team</button></div><div class="faq-list">{''.join(f'<details><summary>{e(q)}<span aria-hidden="true">+</span></summary><div class="faq-answer"><p>{e(a)}</p></div></details>' for q,a in faqs())}</div></div><div class="wrap seo"><details><summary>More about plots on the Indore–Ujjain Road <span aria-hidden="true">+</span></summary><div><h3>Residential plots on the Indore–Ujjain Road</h3><p>For families exploring residential plots near Indore or Ujjain, Valencia Town brings together planned community spaces and room to build a personal home. Its Shahna address on the Indore–Ujjain corridor connects the township with Sri Aurobindo Hospital, Vijay Nagar, the airport and the temple city of Ujjain.</p><p>When considering plots on the Indore–Ujjain Road, visit the location in person, review the current layout documentation and confirm available plot sizes. Our team can help you understand the planned amenities and arrange a private visit.</p></div></details></div></section>'''
def developer():
    D=P['developer']
    if str(D['name']).startswith('TODO'): return ''
    tes=[t for t in P['testimonials'] if not str(t['quote']).startswith('TODO')]
    tes_html=''.join('<blockquote><p>“'+e(t['quote'])+'”</p><footer>'+e(t['name'])+'<span>'+e(t['detail'])+'</span></footer></blockquote>' for t in tes)
    rows=[('Past projects',', '.join(todo(x) for x in D['pastProjects'])),('Construction status',todo(D['constructionStatus'])),('Possession',todo(D['possession'])),('Bank tie-ups',', '.join(todo(x) for x in D['bankTieUps'])),('Sales gallery',todo(D['salesGallery'])+'<br>'+e(D['hours']))]
    return f'''<section class="developer" id="developer" aria-labelledby="developer-title"><div class="wrap faq-grid"><div class="faq-intro"><h2 id="developer-title" class="display display-s">Built by people<br>who stay.</h2><p class="lede">{todo(D['name'])}, part of {todo(D['group'])}. Developing in the region since {todo(D['since'])}.</p></div><dl class="facts-list">{''.join(f'<div><dt>{k}</dt><dd>{v}</dd></div>' for k,v in rows)}</dl></div>{('<div class="wrap testimonials">'+tes_html+'</div>') if tes else ''}</section>'''
def footer():
    return f'''<footer class="footer" id="contact"><div class="wrap footer-grid"><div class="footer-brand">{mark('footer-mark')}<p class="footer-wordmark">Valencia Town</p><p class="footer-tagline">{P['tagline']}</p></div><nav class="footer-col" aria-label="Footer"><a href="#mahakal">Mahakal is calling</a><a href="#location">The road</a><a href="#plan">The plan</a><a href="#life">Life here</a><a href="#plots">Your plot</a><a href="#faq">Questions</a></nav><div class="footer-col"><address>Valencia Town<br>Shahna, Indore–Ujjain Road<br>Madhya Pradesh</address><a class="link" href="https://www.google.com/maps/dir/?api=1&amp;destination={P['latitude']},{P['longitude']}" target="_blank" rel="noopener">Get directions</a></div><div class="footer-col footer-connect"><p>Private visits by appointment, 10 am to 7 pm.<br>Brochure, layout and price list on request.</p><div id="contact-details"></div><a class="whatsapp footer-whatsapp" hidden target="_blank" rel="noopener">{WA_ICON}WhatsApp us</a>{cta(cls='btn')}<p id="rera-line" hidden></p></div></div><div class="wrap footer-legal"><p>Images are artist’s impressions for representation purposes. Specifications, amenities, layouts and drive times are indicative and subject to change.</p><p>© <span id="year">2026</span> Valencia Town. {todo(P['legalEntity'],'Legal entity to be confirmed')} <button class="privacy-link" data-privacy>Privacy</button> <button class="privacy-link" data-terms>Terms</button></p></div></footer><div class="mobile-visit"><a class="call-link" href="{phone_href()}">Call</a><a class="whatsapp" hidden target="_blank" rel="noopener">{WA_ICON}WhatsApp</a>{cta('Private visit',cls='bar-visit')}</div><a class="desktop-whatsapp whatsapp" hidden target="_blank" rel="noopener">{WA_ICON}WhatsApp</a>'''
def modals():
    return '''<dialog id="enquiry-modal" class="enquiry-dialog" aria-labelledby="enquiry-title"><button class="close" data-close aria-label="Close enquiry">×</button><aside class="enquiry-side">'''+mark('enquiry-mark')+'''<div class="enquiry-intro"><h2 id="enquiry-title" class="display display-s">Let’s put down roots.</h2><p>Tell us a little about you. The team will call back to plan your visit.</p></div><div class="enquiry-side-foot"><p>Or reach us directly</p><a href="'''+phone_href()+'''">'''+e(P['SALES_PHONE'])+'''</a><a href="mailto:'''+e(P['SALES_EMAIL'])+'''">'''+e(P['SALES_EMAIL'])+'''</a><p class="fine">Private visits by appointment, 10 am to 7 pm.</p></div></aside><div class="enquiry-main"><form id="enquiry-form" method="post" action="#" novalidate><label for="full-name">Full name</label><input id="full-name" name="name" autocomplete="name" minlength="2" maxlength="80" required placeholder="Your full name"><label for="mobile-number">Mobile number</label><div class="phone-field"><span>+91</span><input id="mobile-number" name="phone" type="tel" autocomplete="tel-national" inputmode="tel" maxlength="16" required pattern="(?:\\+91[ -]?)?[6-9][0-9 -]{9,13}" placeholder="10-digit mobile number" aria-describedby="phone-help"></div><small id="phone-help">Indian mobile number, with or without +91.</small><label for="email">Email <span class="optional">(optional)</span></label><input id="email" name="email" type="email" autocomplete="email" maxlength="120" placeholder="you@example.com"><label for="preferred-time">Preferred time to call <span class="optional">(optional)</span></label><select id="preferred-time" name="preferredTime"><option value="">Any time</option><option>Morning (10 am – 1 pm)</option><option>Afternoon (1 pm – 4 pm)</option><option>Evening (4 pm – 7 pm)</option></select><label for="interest">I’m interested in</label><select id="interest" name="interest"><option>Site Visit</option><option>Price List</option><option>Brochure</option><option>Plot Availability</option><option>Layout</option></select><div class="honeypot" aria-hidden="true"><label>Leave empty<input name="website" tabindex="-1" autocomplete="off"></label></div><p class="form-consent">By sending this request you agree to be contacted about Valencia Town. <button type="button" data-privacy>How your details are used</button></p><button class="btn" type="submit">Send request</button><p id="form-status" role="status" aria-live="polite"></p></form><div id="enquiry-success" hidden><span class="success-mark" aria-hidden="true">✓</span><h3>Request received.</h3><p>The Valencia team will call you to plan your visit and answer your questions.</p><div class="next-steps"><a id="success-download" class="btn" hidden download>Download now</a><a id="success-whatsapp" class="link whatsapp" hidden target="_blank" rel="noopener">'''+WA_ICON+'''Continue on WhatsApp</a></div><button class="link" data-close>Back to Valencia</button></div></div></dialog>
    <dialog id="plan-modal" class="viewer-dialog" aria-labelledby="plan-title"><div class="viewer-bar"><h2 id="plan-title">The masterplan</h2><button class="close" data-close aria-label="Close masterplan">×</button></div><div class="zoom-controls"><button data-zoom="out" aria-label="Zoom out">−</button><output id="zoom-level">100%</output><button data-zoom="in" aria-label="Zoom in">+</button><button data-zoom="reset">Reset</button></div><div class="plan-pan" tabindex="0" aria-label="Zoomable masterplan. Use plus and minus to zoom, scroll or drag to pan."><img id="zoom-image" src="assets/img/master-layout-832.webp" alt="Full Valencia Town masterplan" width="832" height="474"></div><p class="viewer-note">Use + to zoom, drag or scroll to explore, pinch on touch screens. Indicative layout; request the current layout for plot-level details.</p></dialog>
    <dialog id="gallery-modal" class="viewer-dialog gallery-dialog" aria-labelledby="gallery-caption"><button class="close" data-close aria-label="Close gallery">×</button><div class="gallery-viewer"><button data-gallery-prev aria-label="Previous image">←</button><img id="gallery-image" alt=""><button data-gallery-next aria-label="Next image">→</button></div><div class="gallery-viewer-caption"><p id="gallery-caption" aria-live="polite"></p><span>Artist’s impression</span><span id="gallery-count"></span></div></dialog>
    <dialog id="privacy-modal" class="privacy-dialog" aria-labelledby="privacy-title"><button class="close" data-close aria-label="Close privacy details">×</button><h2 id="privacy-title" class="display display-s">How your details are used.</h2><p><strong>Purpose.</strong> When you send a request, your name, mobile number, optional email, preferred time and selected interest are used by the Valencia Town sales team only to respond to that request. The page you were on and campaign referral details may be recorded with it.</p><p><strong>Retention.</strong> Enquiry details are kept for up to 24 months, or until you ask us to remove them, whichever is sooner. They are not sold or shared with third parties for their own marketing.</p><p><strong>Your choices.</strong> To correct or delete your details, write to <a href="mailto:'''+e(P['SALES_EMAIL'])+'''">'''+e(P['SALES_EMAIL'])+'''</a> or tell the team member who contacts you. Please do not include sensitive personal information in your request.</p><p class="fine">Images are artist’s impressions for representation purposes. Specifications, amenities and layouts are indicative and subject to change. <button type="button" class="inline-link" data-terms>Terms of use</button></p></dialog>
    <dialog id="terms-modal" class="privacy-dialog" aria-labelledby="terms-title"><button class="close" data-close aria-label="Close terms">×</button><h2 id="terms-title" class="display display-s">The small print.</h2><p>This website is for information only and does not constitute an offer, invitation or legal commitment. All images are artist’s impressions. Dimensions, areas, amenities, specifications, layouts and drive times are indicative and subject to change without notice.</p><p>Prices, availability and payment plans are confirmed only in writing by '''+todo(P['legalEntity'],'the developer')+'''. Please verify the current project documentation and applicable approvals before making any decision.</p><p class="fine tbc">Legal team to review and complete these terms before launch.</p></dialog>'''
def document():
    url=SITE_URL; description=f'Valencia, The Address of Tomorrow: {P["acres"]} acres of residential plots at Shahna on the Indore–Ujjain Road, forty minutes from Shri Mahakaleshwar, Ujjain. Mahakal is calling you home.'
    schema={'@context':'https://schema.org','@graph':[{'@type':'Place','name':P['name'],'url':url+'/', 'description':description,'address':{'@type':'PostalAddress','streetAddress':'Indore–Ujjain Road','addressLocality':'Shahna','addressRegion':'Madhya Pradesh','addressCountry':'IN'},'geo':{'@type':'GeoCoordinates','latitude':P['latitude'],'longitude':P['longitude']}},{'@type':'FAQPage','mainEntity':[{'@type':'Question','name':q,'acceptedAnswer':{'@type':'Answer','text':a}} for q,a in faqs()]}]}
    head=f'''<!doctype html><html lang="en-IN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"><title>Valencia | The Address of Tomorrow</title><meta name="description" content="{description}"><meta name="theme-color" content="#17231D"><meta name="robots" content="index, follow, max-image-preview:large"><link rel="canonical" href="{url}/"><meta property="og:type" content="website"><meta property="og:locale" content="en_IN"><meta property="og:site_name" content="Valencia Town"><meta property="og:title" content="Valencia — The Address of Tomorrow"><meta property="og:description" content="{description}"><meta property="og:url" content="{url}/"><meta property="og:image" content="{url}/assets/img/og-image.jpg"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="Valencia — The Address of Tomorrow"><meta name="twitter:description" content="{description}"><meta name="twitter:image" content="{url}/assets/img/og-image.jpg"><link rel="icon" href="assets/img/favicon.svg" type="image/svg+xml"><link rel="icon" href="assets/img/favicon.ico" sizes="32x32"><link rel="apple-touch-icon" href="assets/img/apple-touch-icon.png"><link rel="preload" href="assets/fonts/cormorant.woff2" as="font" type="font/woff2" crossorigin><link rel="preload" href="assets/fonts/cormorant-italic.woff2" as="font" type="font/woff2" crossorigin><link rel="preload" href="assets/fonts/dmsans.woff2" as="font" type="font/woff2" crossorigin><link rel="preload" as="image" href="assets/img/hero-signage-1280.webp" imagesrcset="assets/img/hero-signage-640.webp 640w, assets/img/hero-signage-1280.webp 1280w" imagesizes="100vw" media="(min-width: 768px)" fetchpriority="high"><link rel="stylesheet" href="css/style.css?v=20261010f"><script type="application/ld+json">{json.dumps(schema,ensure_ascii=False)}</script></head>'''
    return head+'<body>'+header()+'<main id="main">'+''.join(f() for f in [hero,mahakal,location,plan,life,gallery,plots,visit,faq,developer])+'</main>'+footer()+modals()+f'<script id="project-data" type="application/json">{json.dumps(P,ensure_ascii=False).replace("<","&lt;")}</script><script src="js/main.js?v=20261010f" defer></script></body></html>'
